module.exports = {
  COMMUNITY_CHAT: "COMMUNITY_CHAT",
  USER_CONNECTED: "USER_CONNECTED",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
  MESSAGE_SENT: "MESSAGE_SENT",
  VERIFY_USER: "VERIFY_USER",
  LOGOUT: "LOGOUT",
  TYPING: "TYPING",
  USER_ACTION: "USER_ACTION",
};
